### ISSUE TITLE
PrivacyGuard 在ios使用的时候好像没有生效

### ISSUE THREAD

**Issue by chenjiangmin** [jacklee1995/widgets_easier#2]
```
PrivacyGuard(
 preventScreenshot: true,
 chiild:Container()
)

```

使用的iphone 15 pro
系统是 17.5

异常 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(INVALID_ARGUMENTS, Invalid arguments, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      PrivacyGuardChannel.preventScreenshot (package:widgets_easier/src/channels/privacy_guard_channel.dart:7:5)
<asynchronous suspension>
```

**Comment by jacklee1995** [comment]
反馈收到



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月05日 21:14 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [jacklee1995/widgets_easier] PrivacyGuard 在ios使用的时候好像没有生效 (Issue #2) |

PrivacyGuard(
 preventScreenshot: true,
 chiild:Container()
)



使用的iphone 15 pro
系统是 17.5

异常

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(INVALID_ARGUMENTS, Invalid arguments, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      PrivacyGuardChannel.preventScreenshot (package:widgets_easier/src/channels/privacy_guard_channel.dart:7:5)
<asynchronous suspension>


image.png (view on web)
